repository: dynamsoft-docs/document-normalizer-docs
repositoryUrl: https://github.com/dynamsoft-docs/document-normalizer-docs/blob/main
docFullPath: https://www.dynamsoft.com/document-normalizer/docs-archive/core
firstLevelUrl: /document-normalizer/docs-archive/core
docHomePage: /document-normalizer/docs-archive/core/

introduction: /document-normalizer/docs-archive/core/introduction/

c: /document-normalizer/docs-archive/server/programming/c/
c_api: /document-normalizer/docs-archive/server/programming/c/api-reference/
c_release_notes: /document-normalizer/docs-archive/server/programming/c/release-notes/

cpp: /document-normalizer/docs-archive/server/programming/cplusplus/
cpp_release_notes: /document-normalizer/docs-archive/server/programming/cplusplus/release-notes/

dotnet: /document-normalizer/docs-archive/server/programming/dotnet/
dotnet_release_notes: /document-normalizer/docs-archive/server/programming/dotnet/release-notes/

ios: /document-normalizer/docs-archive/mobile/programming/ios/
ios_release_notes: /document-normalizer/docs-archive/mobile/programming/ios/release-notes/

android: /document-normalizer/docs-archive/mobile/programming/android/
android_release_notes: /document-normalizer/docs-archive/mobile/programming/android/release-notes/

js: /document-normalizer/docs-archive/web/programming/javascript/
js_release_notes: /document-normalizer/docs-archive/web/programming/javascript/release-notes/

xamarin: /document-normalizer/docs-archive/mobile/programming/xamarin/
xamarin_release_notes: /document-normalizer/docs-archive/mobile/programming/xamarin/release-notes/

release_notes: /document-normalizer/docs-archive/core/release-notes/

enumerations: /capture-vision/docs-archive/core/enums/
dcv_parameters: /capture-vision/docs-archive/core/parameters/
parameters_reference: /capture-vision/docs-archive/core/parameters/reference/
parameters_ddn: /document-normalizer/docs-archive/core/parameters/
parameters_reference_ddn: /document-normalizer/docs-archive/core/parameters/reference/
license: /document-normalizer/docs-archive/core/license-activation/

useVersionTree: true

assets: /document-normalizer/docs-archive/core/assets/
edit_icon: /document-normalizer/docs-archive/core/assets/img-icon/edit-icon.png
smile_icon: /document-normalizer/docs-archive/core/assets/img-icon/icon-smile.png
sad_icon: /document-normalizer/docs-archive/core/assets/img-icon/icon-sad.png

baseurl: "/document-normalizer/docs-archive/core"

download: "/document-normalizer/downloads/"

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-webp
  - jekyll-relative-links
  - jekyll-redirect-from
  - jekyll-readme-index
  - jekyll-seo-tag


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope: 
      path: "" 
    values: 
      docRootName: "Document Normalizer" 
      docHomePage: "/document-normalizer/docs-archive/core/introduction/"
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
