repository: dynamsoft-docs/document-normalizer-docs
repositoryUrl: https://github.com/dynamsoft-docs/document-normalizer-docs/blob/main
docFullPath: https://www.dynamsoft.com/document-normalizer/
firstLevelUrl: /document-normalizer
docHomePage: /document-normalizer/introduction/

introduction: /document-normalizer/introduction/
programming: /document-normalizer/programming/
parameters: /document-normalizer/parameters/

c: /document-normalizer/programming/c/
cpp: /document-normalizer/programming/cplusplus/
c_cpp: /document-normalizer/programming/c-cplusplus/
c_cpp_struct: /document-normalizer/programming/c-cplusplus/api-reference/struct/
c_cpp_common_struct: /document-normalizer/programming/c-cplusplus/api-reference/struct/common/

ios: /document-normalizer/programming/objectivec-swift/
ios_api: /document-normalizer/programming/objectivec-swift/api-reference/
ios_release_notes: /document-normalizer/programming/objectivec-swift/release-notes/

android: /document-normalizer/programming/android/
android_api: /document-normalizer/programming/android/api-reference/
android_release_notes: /document-normalizer/programming/android/release-notes/

enumerations: /document-normalizer/parameters/enumerations/
common_enumerations: /document-normalizer/parameters/enumerations/common/
parameter_reference: /document-normalizer/parameters/reference/
parameter_content_normalizer:  /document-normalizer/parameters/reference/document-normalizer-parameter/
parameter_normalization_definition: /document-normalizer/parameters/reference/normalization-definition/

useVersionTree: true

assets: /document-normalizer/assets/
edit_icon: /document-normalizer/assets/img-icon/edit-icon.png
smile_icon: /document-normalizer/assets/img-icon/icon-smile.png
sad_icon: /document-normalizer/assets/img-icon/icon-sad.png
dbr_icon: /document-normalizer/assets/img-icon/icon-dbr.svg
dwt_icon: /document-normalizer/assets/img-icon/icon-dwt.svg
dnt_icon: /document-normalizer/assets/img-icon/icon-dnt.svg

baseurl: "/document-normalizer"

plugins:
  - jemoji
  - jekyll-sitemap


defaults:
  - scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
  - scope:
      path: "Hide_Tree_Page.html"
    values:
      sitemap: false

url: "https://www.dynamsoft.com" # sitemap root
