repository: Dynamsoft/content-normalizer-docs
repositoryUrl: https://github.com/Dynamsoft/content-normalizer-docs/blob/main
docFullPath: https://www.dynamsoft.com/content-normalizer/
firstLevelUrl: /content-normalizer
docHomePage: /content-normalizer/introduction/

introduction: /content-normalizer/introduction/
programming: /content-normalizer/programming/
parameters: /content-normalizer/parameters/

c: /content-normalizer/programming/c/
cpp: /content-normalizer/programming/cplusplus/
c_cpp: /content-normalizer/programming/c-cplusplus/
c_cpp_struct: /content-normalizer/programming/c-cplusplus/api-reference/struct/
c_cpp_common_struct: /content-normalizer/programming/c-cplusplus/api-reference/struct/common/

enumerations: /content-normalizer/parameters/enumerations/
common_enumerations: /content-normalizer/parameters/enumerations/common/
parameter_reference: /content-normalizer/parameters/reference/
parameter_content_normalizer:  /content-normalizer/parameters/reference/content-normalizer-parameter/
parameter_normalization_definition: /content-normalizer/parameters/reference/normalization-definition/

useVersionTree: true

assets: /content-normalizer/assets/
edit_icon: /content-normalizer/assets/img-icon/edit-icon.png
smile_icon: /content-normalizer/assets/img-icon/icon-smile.png
sad_icon: /content-normalizer/assets/img-icon/icon-sad.png
dbr_icon: /content-normalizer/assets/img-icon/icon-dbr.svg
dwt_icon: /content-normalizer/assets/img-icon/icon-dwt.svg
dnt_icon: /content-normalizer/assets/img-icon/icon-dnt.svg

baseurl: "/content-normalizer"

plugins:
  - jemoji


defaults:
  -
    scope:
      path: ""
    values:
      layout: "default-layout"
      noTitleIndex: true
      needAutoGenerateSidebar: true
      needGenerateH3Content: true
